
name: ci 
on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build-test-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json

      - name: Install deps
        working-directory: app
        run: npm ci

      - name: Lint
        working-directory: app
        run: npm run lint

      - name: Unit tests
        working-directory: app
        run: npm test

      - name: Build image (no push)
        run: |
          docker build -t local/app:ci ./app

      - name: Trivy scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: 'local/app:ci'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform fmt/validate
        working-directory: infra
        run: |
          terraform fmt -check
          terraform init -backend=false
          terraform validate
