name: oidc-smoke
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - uses: google-github-actions/setup-gcloud@v2
      - run: gcloud projects describe ${{ vars.GCP_PROJECT_ID }} --format='value(projectId)'
