name: infra-deploy (on PR merge)

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]
    paths:
      - "infra/**"
      - ".github/workflows/infra-deploy-on-pr-merge.yml"

jobs:
  terraform-apply:
    environment: production
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Auth to GCP (OIDC)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Terraform init
        working-directory: infra
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: infra
        env:
          TF_VAR_project_id: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_region: ${{ vars.GCP_REGION }}
          TF_VAR_artifact_registry_repo: ${{ vars.ARTIFACT_REPO || 'apps' }}
          TF_VAR_deployer_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
          TF_VAR_chat_webhook_url: ${{ secrets.CHAT_WEBHOOK_URL }}
          TF_VAR_alert_email: ${{ secrets.ALERT_EMAIL }}
        run: |
          TF_LOG=DEBUG terraform destroy -auto-approve
